model:
  arch_v: 'arch_v2'
  params:
    embed_dim: 128
    n_embed: 256
    ddconfig:
      double_z: False
      z_channels: 128
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult: [1,2,2,4,4]
      num_res_blocks: 1
      attn_resolutions: [8]
      # dropout: 0.0
    decmlpconfig:
        dims: [512, 512, 512, 512]
        num_class: 6
        dropout: [0, 1, 2, 3]
        dropout_prob: 0.2
        norm_layers: [0, 1, 2, 3]
        latent_in: [2]
        xyz_in_all: False
        use_tanh: False
        latent_dropout: False
        weight_norm: True

lossconfig:
  params:
    disc_conditional: False
    disc_in_channels: 1
    disc_start: 250001
    disc_weight: 0.8
    codebook_weight: 1.0
    perceptual_weight: 0.0

data:
  params:
    batch_size: 1
    num_workers: 1
    train:
      params:
        config:
          size: 256
    validation:
      params:
        config:
          size: 256
